USE pizzahut;

-- Retrive total number of orders placed
select count(order_id) from orders;

-- calculate the total revenue generated by pizza saales.
select ROUND(SUM(od.quantity * p.price),2) as total_price
from order_details od join pizzas p ON od.pizza_id = p.pizza_id;

-- Highest price pizza 
select pt.name, p.price 
from pizza_types pt join pizzas p 
on pt.pizza_type_id = p.pizza_type_id order by p.price desc limit 1;

-- Identify most common pizza size ordered
select p.size, sum(od.quantity) as cnt
from pizzas p JOIN order_details od on p.pizza_id = od.pizza_id
group by p.size order by cnt desc limit 1;

-- List the top 5 most ordered pizza types 
-- along with their quantities
select pt.name, sum(od.quantity) as total_pizzas
from pizza_types pt JOIN pizzas p 
ON pt.pizza_type_id = p.pizza_type_id 
JOIN  order_details od ON p.pizza_id = od.pizza_id 
group by pt.name order by total_pizzas desc limit 5;

-- Distribution of orders on time
select hour(order_time) as Hour, count(order_id) as NO_Of_Orders 
from orders 
group by hour order by NO_Of_Orders desc;

-- Distribution of pizzas category-wise
select category, count(name) 
from pizza_types group by category;

-- Group the orders by date and calculate the number
-- of pizzas ordered per day
select round(avg(total_quantity),0)
from (select o.order_date, count(od.quantity) as total_quantity
from orders o JOIN order_details od ON o.order_id = od.order_id
group by o.order_date) as quantity_per_day;


-- Determine the top 3 most ordered pizza type based on revenue
select pt.name, sum(od.quantity*p.price) as revenue
from pizza_types pt join pizzas p on pt.pizza_type_id = p.pizza_type_id 
join order_details od on p.pizza_id = od.pizza_id group by pt.name order by revenue DESC limit 3;

-- Percentage of Revenue by category

select pt.category, round(sum(od.quantity*p.price) / 
(select round(sum(od.quantity*p.price),2) AS total_sales 
from order_details od join pizzas p on od.pizza_id=p.pizza_id )*100, 2) as percentage_sales
from pizzas p join pizza_types pt ON p.pizza_type_id = pt.pizza_type_id 
join order_details od where od.pizza_id = p.pizza_id group by pt.category order by percentage_sales DESC;


-- Cumulative revenue generated over time
select order_date, sum(total_revenue) over(order by order_date) as cum_revenue
from 
(select o.order_date, round(sum(od.quantity*p.price),2) as total_revenue 
from order_details od join orders o on od.order_id = o.order_id 
join pizzas p ON p.pizza_id = od.pizza_id group by o.order_date) as sales_by_date;


